# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RobotUIApp(object):
    def setupUi(self, RobotUIApp):
        RobotUIApp.setObjectName("RobotUIApp")
        RobotUIApp.setEnabled(True)
        RobotUIApp.resize(854, 480)
        RobotUIApp.setMinimumSize(QtCore.QSize(854, 480))
        RobotUIApp.setMaximumSize(QtCore.QSize(3840, 2160))
        self.centralwidget = QtWidgets.QWidget(parent=RobotUIApp)
        self.centralwidget.setObjectName("centralwidget")
        self.nav_primary_camera_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.nav_primary_camera_label.setGeometry(QtCore.QRect(0, 0, 854, 480))
        self.nav_primary_camera_label.setMinimumSize(QtCore.QSize(854, 480))
        self.nav_primary_camera_label.setMaximumSize(QtCore.QSize(3840, 2160))
        self.nav_primary_camera_label.setStyleSheet("color: rgb(22, 51, 79)")
        self.nav_primary_camera_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.nav_primary_camera_label.setLineWidth(0)
        self.nav_primary_camera_label.setText("")
        self.nav_primary_camera_label.setObjectName("nav_primary_camera_label")
        self.nav_secondary_camera_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.nav_secondary_camera_label.setGeometry(QtCore.QRect(30, 30, 220, 140))
        self.nav_secondary_camera_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.nav_secondary_camera_label.setText("")
        self.nav_secondary_camera_label.setObjectName("nav_secondary_camera_label")
        self.snapshot_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.snapshot_button.setGeometry(QtCore.QRect(755, 220, 51, 51))
        self.snapshot_button.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.snapshot_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/dslr-camera.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("img/dslr-camera.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.snapshot_button.setIcon(icon)
        self.snapshot_button.setIconSize(QtCore.QSize(51, 51))
        self.snapshot_button.setFlat(True)
        self.snapshot_button.setObjectName("snapshot_button")
        self.record_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.record_button.setGeometry(QtCore.QRect(760, 300, 40, 40))
        self.record_button.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.record_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/record.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap("img/record.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.record_button.setIcon(icon1)
        self.record_button.setIconSize(QtCore.QSize(51, 51))
        self.record_button.setFlat(True)
        self.record_button.setObjectName("record_button")
        self.speed_display = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.speed_display.setGeometry(QtCore.QRect(270, 400, 121, 51))
        self.speed_display.setAutoFillBackground(False)
        self.speed_display.setStyleSheet("QLabel {\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #ffffff; /* White text */\n"
"    background-color: #2c3e50; /* Dark blue background */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QLCDNumber {\n"
"    background-color: rgb(0, 49, 71); /* Teal color */\n"
"    color: #ffffff; /* White text */\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}")
        self.speed_display.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.speed_display.setObjectName("speed_display")
        self.distance_display = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.distance_display.setGeometry(QtCore.QRect(470, 400, 121, 51))
        self.distance_display.setAutoFillBackground(False)
        self.distance_display.setStyleSheet("QLabel {\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #ffffff; /* White text */\n"
"    background-color: #2c3e50; /* Dark blue background */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QLCDNumber {\n"
"    background-color: rgb(0, 49, 71); /* Teal color */\n"
"    color: #ffffff; /* White text */\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}")
        self.distance_display.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.distance_display.setObjectName("distance_display")
        self.speed_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.speed_label.setGeometry(QtCore.QRect(270, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.speed_label.setFont(font)
        self.speed_label.setStyleSheet("color: rgb(255, 255, 255)")
        self.speed_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.speed_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.speed_label.setObjectName("speed_label")
        self.distance_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.distance_label.setGeometry(QtCore.QRect(470, 360, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.distance_label.setFont(font)
        self.distance_label.setStyleSheet("color: rgb(255, 255, 255)")
        self.distance_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.distance_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.distance_label.setObjectName("distance_label")
        self.primary_battery = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.primary_battery.setGeometry(QtCore.QRect(737, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.primary_battery.setFont(font)
        self.primary_battery.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #2c3e50; /* Dark blue border */\n"
"    border-radius: 8px;\n"
"    background-color: #bdc3c7; /* Light gray background */\n"
"    padding: 5px;  /* Padding around the bar */\n"
"    text-align: right;  /* Center the percentage text */\n"
"    color: #2c3e50; /* Dark blue text */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(31, 167, 88); /* Green color for battery level */\n"
"    width: 20px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.primary_battery.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.primary_battery.setProperty("value", 24)
        self.primary_battery.setObjectName("primary_battery")
        self.secondary_battery = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.secondary_battery.setGeometry(QtCore.QRect(190, 180, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.secondary_battery.setFont(font)
        self.secondary_battery.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #2c3e50; /* Dark blue border */\n"
"    border-radius: 4px;\n"
"    background-color: #bdc3c7; /* Light gray background */\n"
"    padding: 5px;  /* Padding around the bar */\n"
"    text-align: right;  /* Center the percentage text */\n"
"    color: #2c3e50; /* Dark blue text */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(31, 167, 88); /* Green color for battery level */\n"
"    width: 20px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.secondary_battery.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.secondary_battery.setProperty("value", 24)
        self.secondary_battery.setObjectName("secondary_battery")
        self.work_secondary_camera_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.work_secondary_camera_label.setGeometry(QtCore.QRect(30, 30, 220, 140))
        self.work_secondary_camera_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.work_secondary_camera_label.setText("")
        self.work_secondary_camera_label.setObjectName("work_secondary_camera_label")
        self.work_primary_camera_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.work_primary_camera_label.setGeometry(QtCore.QRect(0, 0, 854, 480))
        self.work_primary_camera_label.setMinimumSize(QtCore.QSize(854, 480))
        self.work_primary_camera_label.setMaximumSize(QtCore.QSize(3840, 2160))
        self.work_primary_camera_label.setStyleSheet("color: rgb(22, 51, 79)")
        self.work_primary_camera_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.work_primary_camera_label.setLineWidth(0)
        self.work_primary_camera_label.setText("")
        self.work_primary_camera_label.setObjectName("work_primary_camera_label")
        self.nav_mode_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nav_mode_button.setGeometry(QtCore.QRect(724, 100, 111, 31))
        self.nav_mode_button.setStyleSheet("")
        self.nav_mode_button.setObjectName("nav_mode_button")
        self.work_mode_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.work_mode_button.setGeometry(QtCore.QRect(724, 153, 111, 31))
        self.work_mode_button.setObjectName("work_mode_button")
        self.nav_primary_camera_label.raise_()
        self.nav_secondary_camera_label.raise_()
        self.snapshot_button.raise_()
        self.record_button.raise_()
        self.primary_battery.raise_()
        self.work_primary_camera_label.raise_()
        self.nav_mode_button.raise_()
        self.work_mode_button.raise_()
        self.distance_display.raise_()
        self.distance_label.raise_()
        self.speed_label.raise_()
        self.speed_display.raise_()
        self.secondary_battery.raise_()
        self.work_secondary_camera_label.raise_()
        RobotUIApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(RobotUIApp)
        QtCore.QMetaObject.connectSlotsByName(RobotUIApp)

    def retranslateUi(self, RobotUIApp):
        _translate = QtCore.QCoreApplication.translate
        RobotUIApp.setWindowTitle(_translate("RobotUIApp", "RobotUI"))
        self.speed_label.setText(_translate("RobotUIApp", "Speed (m/s)"))
        self.distance_label.setText(_translate("RobotUIApp", "Distance (m)"))
        self.nav_mode_button.setText(_translate("RobotUIApp", "NAVIGATON MODE"))
        self.work_mode_button.setText(_translate("RobotUIApp", "WORK MODE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RobotUIApp = QtWidgets.QMainWindow()
    ui = Ui_RobotUIApp()
    ui.setupUi(RobotUIApp)
    RobotUIApp.show()
    sys.exit(app.exec())
